# Generated by Django 3.2.19 on 2023-05-25 00:59

import course_discovery.apps.course_metadata.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0325_programsubscriptionconfiguration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseurlslug',
            name='url_slug',
            field=course_discovery.apps.course_metadata.models.AutoSlugWithSlashesField(blank=True, editable=False, max_length=255, populate_from='course__title'),
        ),
    ]
